name: Jekyll Deploy to GitHub Pages

on:
  push:
    branches: [material] # Or your default branch name
  workflow_dispatch:

permissions:
  id-token: write
  pages: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.4

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Build with Jekyll
        run: bundle exec jekyll build --destination _site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: _site
